class InvalidAlg(ValueError): pass
class InvalidClaim(ValueError): pass
class InvalidCiphertext(ValueError): pass
class InvalidHeader(ValueError): pass
class InvalidSerialization(ValueError): pass
class InvalidSignature(Exception): pass
class InvalidUUIDType(ValueError): pass
class NoIssuerSpecified(ValueError): pass
class TokenExpired(Exception): pass
